# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and upload the build artifact to the GitHub Action
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3.0.0
    - name: Use Node.js
      uses: actions/setup-node@v3.1.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    # For faster / safer npm installs in a CI environment
    # https://github.com/actions/setup-node/pull/103#issuecomment-890361838
    - run: npm ci --prefer-offline --no-audit
    - run: npm run build
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: build-for-${{github.sha}}
        path: |
          build/
          public/build/
